import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
const base = 'http://127.0.0.1:3191';
let cookie = '';
let tenantId = '';
async function call(path, method='GET', body, expected=200, origin=base) {
  const res = await fetch(base+path,{method,headers:{'Content-Type':'application/json',Origin:origin,'X-Tenant-Id':tenantId,...(cookie?{Cookie:cookie}:{}),'Idempotency-Key':randomUUID()},...(body===undefined?{}:{body:JSON.stringify(body)})});
  assert.equal(res.status,expected,`${method} ${path}: ${res.status}`);
  const data = await res.json();
  return {data,res};
}
const g = '/api/gateway/';
const choices = (await call('/api/session')).data;
assert.equal(choices.session,null);
assert.equal(choices.tenants.length,2);
assert.ok(!JSON.stringify(choices).includes('token'));
await call(g+'staff/v1/workspace/departures','GET',undefined,401);
await call('/api/session','POST',{tenantId:choices.tenants[0].tenantId},403,'https://untrusted.example');
const selected = await call('/api/session','POST',{tenantId:choices.tenants[0].tenantId});
const setCookie = selected.res.headers.get('set-cookie');
assert.match(setCookie,/HttpOnly/i); assert.match(setCookie,/SameSite=strict/i);
cookie = setCookie.split(';')[0];
tenantId = selected.data.session.tenant.id;
assert.equal(selected.data.session.tenant.id,choices.tenants[0].tenantId);
await call(g+'platform/v1/tenants','POST',{},404);
await call(g+'admin/v1/products','POST',{},403,'https://untrusted.example');
const session = selected.data.session;
const products = (await call(g+'admin/v1/products')).data;
assert.ok(products.length);
const departures = (await call(g+'staff/v1/workspace/departures')).data.items;
const d = departures.find(d=>d.available>0); assert.ok(d);
const party = {[d.categories.find(c=>c.countsTowardCapacity).slug]:1};
const hold = (await call(g+'staff/v1/holds','POST',{departureId:d.id,party},201)).data;
const booking = (await call(g+'staff/v1/bookings','POST',{holdId:hold.holdId,leadName:'Mock Web Smoke Guest',leadEmail:'smoke@example.invalid',source:session.tenant.config.bookingSources[0],pickup:{kind:'selected',location:'Mock smoke hotel',instructions:'Lobby'}},201)).data;
await call(g+`staff/v1/bookings/${booking.bookingId}/confirm`,'POST',{version:1},409);
await call(g+`staff/v1/bookings/${booking.bookingId}/payments`,'POST',{amountMinor:hold.quote.totalMinor,currency:hold.quote.currency,method:session.tenant.config.manualPaymentMethods[0],status:'settled',reference:'MOCK-WEB-SMOKE',reason:'Synthetic web smoke test payment',occurredAt:new Date().toISOString()},201);
await call(g+`staff/v1/bookings/${booking.bookingId}/confirm`,'POST',{version:1},201);
const detail=(await call(g+`staff/v1/bookings/${booking.bookingId}`)).data;
assert.equal(detail.state,'confirmed');assert.equal(detail.balanceMinor,0);assert.ok(detail.expiresAt);
const manifest = (await call(g+`ops/v1/departures/${d.id}/manifest`)).data;
assert.ok(manifest.bookings.some(b=>b.booking_id===booking.bookingId));
assert.ok((await call(g+'ops/v1/audit')).data.length);
assert.ok((await call(g+'staff/v1/workspace/members')).data.items.length);
assert.ok((await call(g+'staff/v1/workspace/summary')).data.confirmed_bookings>=2);
const operationDay = new Intl.DateTimeFormat('en-CA',{timeZone:session.tenant.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(d.starts_at));
const location=(await call(g+'ops/v1/pickup-locations','POST',{slug:`smoke_${randomUUID().replaceAll('-','')}`,name:'Mock Smoke Hotel',kind:'hotel',notes:'Lobby'},201)).data;
const currentPlan=(await call(g+`ops/v1/departures/${d.id}/pickups`)).data;
const planInput={version:currentPlan.plan?.version,notes:'Synthetic pickup sequence',stops:[{bookingId:booking.bookingId,locationId:location.id,pickupAt:new Date(new Date(d.starts_at).getTime()-30*60*1000).toISOString(),notes:'Lobby'}]};
const savedPlan=(await call(g+`ops/v1/departures/${d.id}/pickups`,'POST',planInput,201)).data;
assert.ok(savedPlan.version>=1);
const board=(await call(g+`ops/v1/board?date=${operationDay}`)).data;
assert.equal(board.items.find(x=>x.id===d.id).pickup_planned,1);
assert.equal((await call(g+`ops/v1/departures/${d.id}/pickups`)).data.stops.length,1);
const pickupList=(await call(g+`ops/v1/departures/${d.id}/pickup-list`)).data;
assert.ok(pickupList.stops.some(stop=>stop.lead_name==='Mock Web Smoke Guest'));
assert.ok(!pickupList.exceptions.some(item=>item.booking_id===booking.bookingId));
const amendment=(await call(g+`staff/v1/bookings/${booking.bookingId}/change-quotes`,'POST',{version:detail.version,departureId:d.id,party:{...party,[Object.keys(party)[0]]:2},leadName:'Mock Amended Guest',leadEmail:'amended@example.invalid',pickup:{kind:'selected',location:'Mock meeting point',instructions:'Updated pickup'},reason:'Mock amendment smoke'},201)).data;
const changed=(await call(g+`staff/v1/bookings/${booking.bookingId}/changes`,'POST',{version:detail.version,quoteId:amendment.quoteId},201)).data;
assert.equal(changed.version,detail.version+1);
const updated=(await call(g+`staff/v1/bookings/${booking.bookingId}`)).data;
assert.equal(updated.lead_name,'Mock Amended Guest');
assert.equal(updated.party[Object.keys(party)[0]],2);
await call(g+`staff/v1/bookings/${booking.bookingId}/cancel`,'POST',{version:changed.version,reason:'Mock smoke cancellation'},201);
assert.equal((await call(g+`staff/v1/bookings/${booking.bookingId}`)).data.state,'cancelled');
assert.equal((await call(g+`staff/v1/bookings/${booking.bookingId}/changes`)).data.length,2);
assert.ok(!(await call(g+`ops/v1/departures/${d.id}/manifest`)).data.bookings.some(b=>b.booking_id===booking.bookingId));
assert.equal((await call(g+`ops/v1/departures/${d.id}/pickups`)).data.stops.length,0);
const next = await call('/api/session','POST',{tenantId:choices.tenants[1].tenantId});
cookie=next.res.headers.get('set-cookie').split(';')[0];
assert.equal(next.data.session.tenant.id,choices.tenants[1].tenantId);
await call(g+'staff/v1/holds','POST',{departureId:d.id,party},409);
tenantId = next.data.session.tenant.id;
await call(g+`staff/v1/bookings/${booking.bookingId}`,'GET',undefined,404);
await call(g+`ops/v1/departures/${d.id}/manifest`,'GET',undefined,404);
await call(g+`ops/v1/departures/${d.id}/pickup-list`,'GET',undefined,404);
assert.equal((await call(g+'staff/v1/workspace/reservations?search=Mock%20Web%20Smoke')).data.items.length,0);
await call('/api/session','DELETE');cookie='';
await call(g+'staff/v1/workspace/departures','GET',undefined,401);
for (const path of ['/','/reservations','/departures','/operations',`/operations/${d.id}/pickup-list`,'/catalog','/team','/settings','/audit']) {
  const res=await fetch(base+path);assert.equal(res.status,200,path);assert.match(await res.text(),/Zettaz/);
}
console.log('PASS: HTTP session cookies, origin guard, route allowlist, booking/amendment/cancellation/manifest/pickup-plan flow, tenant switching/isolation, logout and web page responses. Browser interaction was not tested.');
