export type CountryOption = {
  code: string;
  name: string;
  currency: string;
  timezone: string;
};

export const COUNTRIES: CountryOption[] = [
  { code: "AF", name: "Afghanistan", currency: "AFN", timezone: "Asia/Kabul" },
  { code: "AX", name: "Åland Islands", currency: "EUR", timezone: "Europe/Helsinki" },
  { code: "AL", name: "Albania", currency: "ALL", timezone: "Europe/Tirane" },
  { code: "DZ", name: "Algeria", currency: "DZD", timezone: "Africa/Algiers" },
  { code: "AS", name: "American Samoa", currency: "USD", timezone: "Pacific/Pago_Pago" },
  { code: "AD", name: "Andorra", currency: "EUR", timezone: "Europe/Andorra" },
  { code: "AO", name: "Angola", currency: "AOA", timezone: "Africa/Luanda" },
  { code: "AI", name: "Anguilla", currency: "XCD", timezone: "America/Anguilla" },
  { code: "AQ", name: "Antarctica", currency: "USD", timezone: "Antarctica/McMurdo" },
  { code: "AG", name: "Antigua & Barbuda", currency: "XCD", timezone: "America/Antigua" },
  { code: "AR", name: "Argentina", currency: "ARS", timezone: "America/Argentina/Buenos_Aires" },
  { code: "AM", name: "Armenia", currency: "AMD", timezone: "Asia/Yerevan" },
  { code: "AW", name: "Aruba", currency: "AWG", timezone: "America/Aruba" },
  { code: "AU", name: "Australia", currency: "AUD", timezone: "Australia/Sydney" },
  { code: "AT", name: "Austria", currency: "EUR", timezone: "Europe/Vienna" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", timezone: "Asia/Baku" },
  { code: "BS", name: "Bahamas", currency: "BSD", timezone: "America/Nassau" },
  { code: "BH", name: "Bahrain", currency: "BHD", timezone: "Asia/Bahrain" },
  { code: "BD", name: "Bangladesh", currency: "BDT", timezone: "Asia/Dhaka" },
  { code: "BB", name: "Barbados", currency: "BBD", timezone: "America/Barbados" },
  { code: "BY", name: "Belarus", currency: "BYN", timezone: "Europe/Minsk" },
  { code: "BE", name: "Belgium", currency: "EUR", timezone: "Europe/Brussels" },
  { code: "BZ", name: "Belize", currency: "BZD", timezone: "America/Belize" },
  { code: "BJ", name: "Benin", currency: "XOF", timezone: "Africa/Porto-Novo" },
  { code: "BM", name: "Bermuda", currency: "BMD", timezone: "Atlantic/Bermuda" },
  { code: "BT", name: "Bhutan", currency: "BTN", timezone: "Asia/Thimphu" },
  { code: "BO", name: "Bolivia", currency: "BOB", timezone: "America/La_Paz" },
  { code: "BA", name: "Bosnia & Herzegovina", currency: "BAM", timezone: "Europe/Sarajevo" },
  { code: "BW", name: "Botswana", currency: "BWP", timezone: "Africa/Gaborone" },
  { code: "BV", name: "Bouvet Island", currency: "NOK", timezone: "UTC" },
  { code: "BR", name: "Brazil", currency: "BRL", timezone: "America/Sao_Paulo" },
  { code: "IO", name: "British Indian Ocean Territory", currency: "USD", timezone: "Indian/Chagos" },
  { code: "VG", name: "British Virgin Islands", currency: "USD", timezone: "America/Tortola" },
  { code: "BN", name: "Brunei", currency: "BND", timezone: "Asia/Brunei" },
  { code: "BG", name: "Bulgaria", currency: "BGN", timezone: "Europe/Sofia" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", timezone: "Africa/Ouagadougou" },
  { code: "BI", name: "Burundi", currency: "BIF", timezone: "Africa/Bujumbura" },
  { code: "KH", name: "Cambodia", currency: "KHR", timezone: "Asia/Phnom_Penh" },
  { code: "CM", name: "Cameroon", currency: "XAF", timezone: "Africa/Douala" },
  { code: "CA", name: "Canada", currency: "CAD", timezone: "America/Toronto" },
  { code: "CV", name: "Cape Verde", currency: "CVE", timezone: "Atlantic/Cape_Verde" },
  { code: "BQ", name: "Caribbean Netherlands", currency: "USD", timezone: "America/Kralendijk" },
  { code: "KY", name: "Cayman Islands", currency: "KYD", timezone: "America/Cayman" },
  { code: "CF", name: "Central African Republic", currency: "XAF", timezone: "Africa/Bangui" },
  { code: "TD", name: "Chad", currency: "XAF", timezone: "Africa/Ndjamena" },
  { code: "CL", name: "Chile", currency: "CLP", timezone: "America/Santiago" },
  { code: "CN", name: "China", currency: "CNY", timezone: "Asia/Shanghai" },
  { code: "CX", name: "Christmas Island", currency: "AUD", timezone: "Indian/Christmas" },
  { code: "CC", name: "Cocos (Keeling) Islands", currency: "AUD", timezone: "Indian/Cocos" },
  { code: "CO", name: "Colombia", currency: "COP", timezone: "America/Bogota" },
  { code: "KM", name: "Comoros", currency: "KMF", timezone: "Indian/Comoro" },
  { code: "CG", name: "Congo - Brazzaville", currency: "XAF", timezone: "Africa/Brazzaville" },
  { code: "CD", name: "Congo - Kinshasa", currency: "CDF", timezone: "Africa/Kinshasa" },
  { code: "CK", name: "Cook Islands", currency: "NZD", timezone: "Pacific/Rarotonga" },
  { code: "CR", name: "Costa Rica", currency: "CRC", timezone: "America/Costa_Rica" },
  { code: "CI", name: "Côte d’Ivoire", currency: "XOF", timezone: "Africa/Abidjan" },
  { code: "HR", name: "Croatia", currency: "EUR", timezone: "Europe/Zagreb" },
  { code: "CU", name: "Cuba", currency: "CUP", timezone: "America/Havana" },
  { code: "CW", name: "Curaçao", currency: "ANG", timezone: "America/Curacao" },
  { code: "CY", name: "Cyprus", currency: "EUR", timezone: "Asia/Nicosia" },
  { code: "CZ", name: "Czechia", currency: "CZK", timezone: "Europe/Prague" },
  { code: "DK", name: "Denmark", currency: "DKK", timezone: "Europe/Copenhagen" },
  { code: "DJ", name: "Djibouti", currency: "DJF", timezone: "Africa/Djibouti" },
  { code: "DM", name: "Dominica", currency: "XCD", timezone: "America/Dominica" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", timezone: "America/Santo_Domingo" },
  { code: "EC", name: "Ecuador", currency: "USD", timezone: "America/Guayaquil" },
  { code: "EG", name: "Egypt", currency: "EGP", timezone: "Africa/Cairo" },
  { code: "SV", name: "El Salvador", currency: "USD", timezone: "America/El_Salvador" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", timezone: "Africa/Malabo" },
  { code: "ER", name: "Eritrea", currency: "ERN", timezone: "Africa/Asmara" },
  { code: "EE", name: "Estonia", currency: "EUR", timezone: "Europe/Tallinn" },
  { code: "SZ", name: "Eswatini", currency: "SZL", timezone: "Africa/Mbabane" },
  { code: "ET", name: "Ethiopia", currency: "ETB", timezone: "Africa/Addis_Ababa" },
  { code: "FK", name: "Falkland Islands", currency: "FKP", timezone: "Atlantic/Stanley" },
  { code: "FO", name: "Faroe Islands", currency: "DKK", timezone: "Atlantic/Faroe" },
  { code: "FJ", name: "Fiji", currency: "FJD", timezone: "Pacific/Fiji" },
  { code: "FI", name: "Finland", currency: "EUR", timezone: "Europe/Helsinki" },
  { code: "FR", name: "France", currency: "EUR", timezone: "Europe/Paris" },
  { code: "GF", name: "French Guiana", currency: "EUR", timezone: "America/Cayenne" },
  { code: "PF", name: "French Polynesia", currency: "XPF", timezone: "Pacific/Tahiti" },
  { code: "TF", name: "French Southern Territories", currency: "EUR", timezone: "Indian/Kerguelen" },
  { code: "GA", name: "Gabon", currency: "XAF", timezone: "Africa/Libreville" },
  { code: "GM", name: "Gambia", currency: "GMD", timezone: "Africa/Banjul" },
  { code: "GE", name: "Georgia", currency: "GEL", timezone: "Asia/Tbilisi" },
  { code: "DE", name: "Germany", currency: "EUR", timezone: "Europe/Berlin" },
  { code: "GH", name: "Ghana", currency: "GHS", timezone: "Africa/Accra" },
  { code: "GI", name: "Gibraltar", currency: "GIP", timezone: "Europe/Gibraltar" },
  { code: "GR", name: "Greece", currency: "EUR", timezone: "Europe/Athens" },
  { code: "GL", name: "Greenland", currency: "DKK", timezone: "America/Godthab" },
  { code: "GD", name: "Grenada", currency: "XCD", timezone: "America/Grenada" },
  { code: "GP", name: "Guadeloupe", currency: "EUR", timezone: "America/Guadeloupe" },
  { code: "GU", name: "Guam", currency: "USD", timezone: "Pacific/Guam" },
  { code: "GT", name: "Guatemala", currency: "GTQ", timezone: "America/Guatemala" },
  { code: "GG", name: "Guernsey", currency: "GBP", timezone: "Europe/Guernsey" },
  { code: "GN", name: "Guinea", currency: "GNF", timezone: "Africa/Conakry" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", timezone: "Africa/Bissau" },
  { code: "GY", name: "Guyana", currency: "GYD", timezone: "America/Guyana" },
  { code: "HT", name: "Haiti", currency: "HTG", timezone: "America/Port-au-Prince" },
  { code: "HM", name: "Heard & McDonald Islands", currency: "AUD", timezone: "UTC" },
  { code: "HN", name: "Honduras", currency: "HNL", timezone: "America/Tegucigalpa" },
  { code: "HK", name: "Hong Kong SAR China", currency: "HKD", timezone: "Asia/Hong_Kong" },
  { code: "HU", name: "Hungary", currency: "HUF", timezone: "Europe/Budapest" },
  { code: "IS", name: "Iceland", currency: "ISK", timezone: "Atlantic/Reykjavik" },
  { code: "IN", name: "India", currency: "INR", timezone: "Asia/Kolkata" },
  { code: "ID", name: "Indonesia", currency: "IDR", timezone: "Asia/Jakarta" },
  { code: "IR", name: "Iran", currency: "IRR", timezone: "Asia/Tehran" },
  { code: "IQ", name: "Iraq", currency: "IQD", timezone: "Asia/Baghdad" },
  { code: "IE", name: "Ireland", currency: "EUR", timezone: "Europe/Dublin" },
  { code: "IM", name: "Isle of Man", currency: "GBP", timezone: "Europe/Isle_of_Man" },
  { code: "IL", name: "Israel", currency: "ILS", timezone: "Asia/Jerusalem" },
  { code: "IT", name: "Italy", currency: "EUR", timezone: "Europe/Rome" },
  { code: "JM", name: "Jamaica", currency: "JMD", timezone: "America/Jamaica" },
  { code: "JP", name: "Japan", currency: "JPY", timezone: "Asia/Tokyo" },
  { code: "JE", name: "Jersey", currency: "GBP", timezone: "Europe/Jersey" },
  { code: "JO", name: "Jordan", currency: "JOD", timezone: "Asia/Amman" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", timezone: "Asia/Almaty" },
  { code: "KE", name: "Kenya", currency: "KES", timezone: "Africa/Nairobi" },
  { code: "KI", name: "Kiribati", currency: "AUD", timezone: "Pacific/Tarawa" },
  { code: "KW", name: "Kuwait", currency: "KWD", timezone: "Asia/Kuwait" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", timezone: "Asia/Bishkek" },
  { code: "LA", name: "Laos", currency: "LAK", timezone: "Asia/Vientiane" },
  { code: "LV", name: "Latvia", currency: "EUR", timezone: "Europe/Riga" },
  { code: "LB", name: "Lebanon", currency: "LBP", timezone: "Asia/Beirut" },
  { code: "LS", name: "Lesotho", currency: "LSL", timezone: "Africa/Maseru" },
  { code: "LR", name: "Liberia", currency: "LRD", timezone: "Africa/Monrovia" },
  { code: "LY", name: "Libya", currency: "LYD", timezone: "Africa/Tripoli" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", timezone: "Europe/Vaduz" },
  { code: "LT", name: "Lithuania", currency: "EUR", timezone: "Europe/Vilnius" },
  { code: "LU", name: "Luxembourg", currency: "EUR", timezone: "Europe/Luxembourg" },
  { code: "MO", name: "Macao SAR China", currency: "MOP", timezone: "Asia/Macau" },
  { code: "MG", name: "Madagascar", currency: "MGA", timezone: "Indian/Antananarivo" },
  { code: "MW", name: "Malawi", currency: "MWK", timezone: "Africa/Blantyre" },
  { code: "MY", name: "Malaysia", currency: "MYR", timezone: "Asia/Kuala_Lumpur" },
  { code: "MV", name: "Maldives", currency: "MVR", timezone: "Indian/Maldives" },
  { code: "ML", name: "Mali", currency: "XOF", timezone: "Africa/Bamako" },
  { code: "MT", name: "Malta", currency: "EUR", timezone: "Europe/Malta" },
  { code: "MH", name: "Marshall Islands", currency: "USD", timezone: "Pacific/Majuro" },
  { code: "MQ", name: "Martinique", currency: "EUR", timezone: "America/Martinique" },
  { code: "MR", name: "Mauritania", currency: "MRU", timezone: "Africa/Nouakchott" },
  { code: "MU", name: "Mauritius", currency: "MUR", timezone: "Indian/Mauritius" },
  { code: "YT", name: "Mayotte", currency: "EUR", timezone: "Indian/Mayotte" },
  { code: "MX", name: "Mexico", currency: "MXN", timezone: "America/Mexico_City" },
  { code: "FM", name: "Micronesia", currency: "USD", timezone: "Pacific/Pohnpei" },
  { code: "MD", name: "Moldova", currency: "MDL", timezone: "Europe/Chisinau" },
  { code: "MC", name: "Monaco", currency: "EUR", timezone: "Europe/Monaco" },
  { code: "MN", name: "Mongolia", currency: "MNT", timezone: "Asia/Ulaanbaatar" },
  { code: "ME", name: "Montenegro", currency: "EUR", timezone: "Europe/Podgorica" },
  { code: "MS", name: "Montserrat", currency: "XCD", timezone: "America/Montserrat" },
  { code: "MA", name: "Morocco", currency: "MAD", timezone: "Africa/Casablanca" },
  { code: "MZ", name: "Mozambique", currency: "MZN", timezone: "Africa/Maputo" },
  { code: "MM", name: "Myanmar (Burma)", currency: "MMK", timezone: "Asia/Rangoon" },
  { code: "NA", name: "Namibia", currency: "NAD", timezone: "Africa/Windhoek" },
  { code: "NR", name: "Nauru", currency: "AUD", timezone: "Pacific/Nauru" },
  { code: "NP", name: "Nepal", currency: "NPR", timezone: "Asia/Kathmandu" },
  { code: "NL", name: "Netherlands", currency: "EUR", timezone: "Europe/Amsterdam" },
  { code: "NC", name: "New Caledonia", currency: "XPF", timezone: "Pacific/Noumea" },
  { code: "NZ", name: "New Zealand", currency: "NZD", timezone: "Pacific/Auckland" },
  { code: "NI", name: "Nicaragua", currency: "NIO", timezone: "America/Managua" },
  { code: "NE", name: "Niger", currency: "XOF", timezone: "Africa/Niamey" },
  { code: "NG", name: "Nigeria", currency: "NGN", timezone: "Africa/Lagos" },
  { code: "NU", name: "Niue", currency: "NZD", timezone: "Pacific/Niue" },
  { code: "NF", name: "Norfolk Island", currency: "AUD", timezone: "Pacific/Norfolk" },
  { code: "KP", name: "North Korea", currency: "KPW", timezone: "Asia/Pyongyang" },
  { code: "MK", name: "North Macedonia", currency: "MKD", timezone: "Europe/Skopje" },
  { code: "MP", name: "Northern Mariana Islands", currency: "USD", timezone: "Pacific/Saipan" },
  { code: "NO", name: "Norway", currency: "NOK", timezone: "Europe/Oslo" },
  { code: "OM", name: "Oman", currency: "OMR", timezone: "Asia/Muscat" },
  { code: "PK", name: "Pakistan", currency: "PKR", timezone: "Asia/Karachi" },
  { code: "PW", name: "Palau", currency: "USD", timezone: "Pacific/Palau" },
  { code: "PS", name: "Palestinian Territories", currency: "ILS", timezone: "Asia/Gaza" },
  { code: "PA", name: "Panama", currency: "PAB", timezone: "America/Panama" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", timezone: "Pacific/Port_Moresby" },
  { code: "PY", name: "Paraguay", currency: "PYG", timezone: "America/Asuncion" },
  { code: "PE", name: "Peru", currency: "PEN", timezone: "America/Lima" },
  { code: "PH", name: "Philippines", currency: "PHP", timezone: "Asia/Manila" },
  { code: "PN", name: "Pitcairn Islands", currency: "NZD", timezone: "Pacific/Pitcairn" },
  { code: "PL", name: "Poland", currency: "PLN", timezone: "Europe/Warsaw" },
  { code: "PT", name: "Portugal", currency: "EUR", timezone: "Europe/Lisbon" },
  { code: "PR", name: "Puerto Rico", currency: "USD", timezone: "America/Puerto_Rico" },
  { code: "QA", name: "Qatar", currency: "QAR", timezone: "Asia/Qatar" },
  { code: "RE", name: "Réunion", currency: "EUR", timezone: "Indian/Reunion" },
  { code: "RO", name: "Romania", currency: "RON", timezone: "Europe/Bucharest" },
  { code: "RU", name: "Russia", currency: "RUB", timezone: "Europe/Moscow" },
  { code: "RW", name: "Rwanda", currency: "RWF", timezone: "Africa/Kigali" },
  { code: "WS", name: "Samoa", currency: "WST", timezone: "Pacific/Apia" },
  { code: "SM", name: "San Marino", currency: "EUR", timezone: "Europe/San_Marino" },
  { code: "ST", name: "São Tomé & Príncipe", currency: "STN", timezone: "Africa/Sao_Tome" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", timezone: "Asia/Riyadh" },
  { code: "SN", name: "Senegal", currency: "XOF", timezone: "Africa/Dakar" },
  { code: "RS", name: "Serbia", currency: "RSD", timezone: "Europe/Belgrade" },
  { code: "SC", name: "Seychelles", currency: "SCR", timezone: "Indian/Mahe" },
  { code: "SL", name: "Sierra Leone", currency: "SLL", timezone: "Africa/Freetown" },
  { code: "SG", name: "Singapore", currency: "SGD", timezone: "Asia/Singapore" },
  { code: "SX", name: "Sint Maarten", currency: "ANG", timezone: "America/Lower_Princes" },
  { code: "SK", name: "Slovakia", currency: "EUR", timezone: "Europe/Bratislava" },
  { code: "SI", name: "Slovenia", currency: "EUR", timezone: "Europe/Ljubljana" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", timezone: "Pacific/Guadalcanal" },
  { code: "SO", name: "Somalia", currency: "SOS", timezone: "Africa/Mogadishu" },
  { code: "ZA", name: "South Africa", currency: "ZAR", timezone: "Africa/Johannesburg" },
  { code: "GS", name: "South Georgia & South Sandwich Islands", currency: "GBP", timezone: "Atlantic/South_Georgia" },
  { code: "KR", name: "South Korea", currency: "KRW", timezone: "Asia/Seoul" },
  { code: "SS", name: "South Sudan", currency: "SSP", timezone: "Africa/Juba" },
  { code: "ES", name: "Spain", currency: "EUR", timezone: "Europe/Madrid" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", timezone: "Asia/Colombo" },
  { code: "BL", name: "St. Barthélemy", currency: "EUR", timezone: "America/St_Barthelemy" },
  { code: "SH", name: "St. Helena", currency: "SHP", timezone: "Atlantic/St_Helena" },
  { code: "KN", name: "St. Kitts & Nevis", currency: "XCD", timezone: "America/St_Kitts" },
  { code: "LC", name: "St. Lucia", currency: "XCD", timezone: "America/St_Lucia" },
  { code: "MF", name: "St. Martin", currency: "EUR", timezone: "America/Marigot" },
  { code: "PM", name: "St. Pierre & Miquelon", currency: "EUR", timezone: "America/Miquelon" },
  { code: "VC", name: "St. Vincent & Grenadines", currency: "XCD", timezone: "America/St_Vincent" },
  { code: "SD", name: "Sudan", currency: "SDG", timezone: "Africa/Khartoum" },
  { code: "SR", name: "Suriname", currency: "SRD", timezone: "America/Paramaribo" },
  { code: "SJ", name: "Svalbard & Jan Mayen", currency: "NOK", timezone: "Arctic/Longyearbyen" },
  { code: "SE", name: "Sweden", currency: "SEK", timezone: "Europe/Stockholm" },
  { code: "CH", name: "Switzerland", currency: "CHF", timezone: "Europe/Zurich" },
  { code: "SY", name: "Syria", currency: "SYP", timezone: "Asia/Damascus" },
  { code: "TW", name: "Taiwan", currency: "TWD", timezone: "Asia/Taipei" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", timezone: "Asia/Dushanbe" },
  { code: "TZ", name: "Tanzania", currency: "TZS", timezone: "Africa/Dar_es_Salaam" },
  { code: "TH", name: "Thailand", currency: "THB", timezone: "Asia/Bangkok" },
  { code: "TL", name: "Timor-Leste", currency: "USD", timezone: "Asia/Dili" },
  { code: "TG", name: "Togo", currency: "XOF", timezone: "Africa/Lome" },
  { code: "TK", name: "Tokelau", currency: "NZD", timezone: "Pacific/Fakaofo" },
  { code: "TO", name: "Tonga", currency: "TOP", timezone: "Pacific/Tongatapu" },
  { code: "TT", name: "Trinidad & Tobago", currency: "TTD", timezone: "America/Port_of_Spain" },
  { code: "TN", name: "Tunisia", currency: "TND", timezone: "Africa/Tunis" },
  { code: "TR", name: "Türkiye", currency: "TRY", timezone: "Europe/Istanbul" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", timezone: "Asia/Ashgabat" },
  { code: "TC", name: "Turks & Caicos Islands", currency: "USD", timezone: "America/Grand_Turk" },
  { code: "TV", name: "Tuvalu", currency: "AUD", timezone: "Pacific/Funafuti" },
  { code: "UM", name: "U.S. Outlying Islands", currency: "USD", timezone: "Pacific/Wake" },
  { code: "VI", name: "U.S. Virgin Islands", currency: "USD", timezone: "America/St_Thomas" },
  { code: "UG", name: "Uganda", currency: "UGX", timezone: "Africa/Kampala" },
  { code: "UA", name: "Ukraine", currency: "UAH", timezone: "Europe/Kiev" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", timezone: "Asia/Dubai" },
  { code: "GB", name: "United Kingdom", currency: "GBP", timezone: "Europe/London" },
  { code: "US", name: "United States", currency: "USD", timezone: "America/New_York" },
  { code: "UY", name: "Uruguay", currency: "UYU", timezone: "America/Montevideo" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", timezone: "Asia/Tashkent" },
  { code: "VU", name: "Vanuatu", currency: "VUV", timezone: "Pacific/Efate" },
  { code: "VA", name: "Vatican City", currency: "EUR", timezone: "Europe/Vatican" },
  { code: "VE", name: "Venezuela", currency: "VES", timezone: "America/Caracas" },
  { code: "VN", name: "Vietnam", currency: "VND", timezone: "Asia/Ho_Chi_Minh" },
  { code: "WF", name: "Wallis & Futuna", currency: "XPF", timezone: "Pacific/Wallis" },
  { code: "EH", name: "Western Sahara", currency: "MAD", timezone: "Africa/El_Aaiun" },
  { code: "YE", name: "Yemen", currency: "YER", timezone: "Asia/Aden" },
  { code: "ZM", name: "Zambia", currency: "ZMW", timezone: "Africa/Lusaka" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", timezone: "Africa/Harare" },
];

/** Deduplicated, sorted list of IANA timezone identifiers. */
export const TIMEZONES: string[] = [
  "Africa/Abidjan",
  "Africa/Accra",
  "Africa/Addis_Ababa",
  "Africa/Algiers",
  "Africa/Asmara",
  "Africa/Bamako",
  "Africa/Bangui",
  "Africa/Banjul",
  "Africa/Bissau",
  "Africa/Blantyre",
  "Africa/Brazzaville",
  "Africa/Bujumbura",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Conakry",
  "Africa/Dakar",
  "Africa/Dar_es_Salaam",
  "Africa/Djibouti",
  "Africa/Douala",
  "Africa/El_Aaiun",
  "Africa/Freetown",
  "Africa/Gaborone",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Juba",
  "Africa/Kampala",
  "Africa/Khartoum",
  "Africa/Kigali",
  "Africa/Kinshasa",
  "Africa/Lagos",
  "Africa/Libreville",
  "Africa/Lome",
  "Africa/Luanda",
  "Africa/Lusaka",
  "Africa/Malabo",
  "Africa/Maputo",
  "Africa/Maseru",
  "Africa/Mbabane",
  "Africa/Mogadishu",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Niamey",
  "Africa/Nouakchott",
  "Africa/Ouagadougou",
  "Africa/Porto-Novo",
  "Africa/Sao_Tome",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Anguilla",
  "America/Antigua",
  "America/Argentina/Buenos_Aires",
  "America/Aruba",
  "America/Asuncion",
  "America/Barbados",
  "America/Belize",
  "America/Bogota",
  "America/Caracas",
  "America/Cayenne",
  "America/Cayman",
  "America/Costa_Rica",
  "America/Curacao",
  "America/Dominica",
  "America/El_Salvador",
  "America/Godthab",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Havana",
  "America/Jamaica",
  "America/Kralendijk",
  "America/La_Paz",
  "America/Lima",
  "America/Lower_Princes",
  "America/Managua",
  "America/Marigot",
  "America/Martinique",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Montevideo",
  "America/Montserrat",
  "America/Nassau",
  "America/New_York",
  "America/Panama",
  "America/Paramaribo",
  "America/Port-au-Prince",
  "America/Port_of_Spain",
  "America/Puerto_Rico",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/St_Barthelemy",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Tegucigalpa",
  "America/Toronto",
  "America/Tortola",
  "Antarctica/McMurdo",
  "Arctic/Longyearbyen",
  "Asia/Aden",
  "Asia/Almaty",
  "Asia/Amman",
  "Asia/Ashgabat",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Colombo",
  "Asia/Damascus",
  "Asia/Dhaka",
  "Asia/Dili",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Gaza",
  "Asia/Ho_Chi_Minh",
  "Asia/Hong_Kong",
  "Asia/Jakarta",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Karachi",
  "Asia/Kathmandu",
  "Asia/Kolkata",
  "Asia/Kuala_Lumpur",
  "Asia/Kuwait",
  "Asia/Macau",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Phnom_Penh",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Thimphu",
  "Asia/Tokyo",
  "Asia/Ulaanbaatar",
  "Asia/Vientiane",
  "Asia/Yerevan",
  "Atlantic/Bermuda",
  "Atlantic/Cape_Verde",
  "Atlantic/Faroe",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/St_Helena",
  "Atlantic/Stanley",
  "Australia/Sydney",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Athens",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Guernsey",
  "Europe/Helsinki",
  "Europe/Isle_of_Man",
  "Europe/Istanbul",
  "Europe/Jersey",
  "Europe/Kiev",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Podgorica",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/San_Marino",
  "Europe/Sarajevo",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zurich",
  "Indian/Antananarivo",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Comoro",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Mayotte",
  "Indian/Reunion",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Efate",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Majuro",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Pohnpei",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Wake",
  "Pacific/Wallis",
  "UTC",
];

/** Deduplicated, sorted list of ISO 4217 currency codes. */
export const CURRENCIES: string[] = [
  "AED",
  "AFN",
  "ALL",
  "AMD",
  "ANG",
  "AOA",
  "ARS",
  "AUD",
  "AWG",
  "AZN",
  "BAM",
  "BBD",
  "BDT",
  "BGN",
  "BHD",
  "BIF",
  "BMD",
  "BND",
  "BOB",
  "BRL",
  "BSD",
  "BTN",
  "BWP",
  "BYN",
  "BZD",
  "CAD",
  "CDF",
  "CHF",
  "CLP",
  "CNY",
  "COP",
  "CRC",
  "CUP",
  "CVE",
  "CZK",
  "DJF",
  "DKK",
  "DOP",
  "DZD",
  "EGP",
  "ERN",
  "ETB",
  "EUR",
  "FJD",
  "FKP",
  "GBP",
  "GEL",
  "GHS",
  "GIP",
  "GMD",
  "GNF",
  "GTQ",
  "GYD",
  "HKD",
  "HNL",
  "HTG",
  "HUF",
  "IDR",
  "ILS",
  "INR",
  "IQD",
  "IRR",
  "ISK",
  "JMD",
  "JOD",
  "JPY",
  "KES",
  "KGS",
  "KHR",
  "KMF",
  "KPW",
  "KRW",
  "KWD",
  "KYD",
  "KZT",
  "LAK",
  "LBP",
  "LKR",
  "LRD",
  "LSL",
  "LYD",
  "MAD",
  "MDL",
  "MGA",
  "MKD",
  "MMK",
  "MNT",
  "MOP",
  "MRU",
  "MUR",
  "MVR",
  "MWK",
  "MXN",
  "MYR",
  "MZN",
  "NAD",
  "NGN",
  "NIO",
  "NOK",
  "NPR",
  "NZD",
  "OMR",
  "PAB",
  "PEN",
  "PGK",
  "PHP",
  "PKR",
  "PLN",
  "PYG",
  "QAR",
  "RON",
  "RSD",
  "RUB",
  "RWF",
  "SAR",
  "SBD",
  "SCR",
  "SDG",
  "SEK",
  "SGD",
  "SHP",
  "SLL",
  "SOS",
  "SRD",
  "SSP",
  "STN",
  "SYP",
  "SZL",
  "THB",
  "TJS",
  "TMT",
  "TND",
  "TOP",
  "TRY",
  "TTD",
  "TWD",
  "TZS",
  "UAH",
  "UGX",
  "USD",
  "UYU",
  "UZS",
  "VES",
  "VND",
  "VUV",
  "WST",
  "XAF",
  "XCD",
  "XOF",
  "XPF",
  "YER",
  "ZAR",
  "ZMW",
  "ZWL",
];

/** Returns the display name for a country code, or the code itself if not found. */
export function countryName(code: string): string {
  return COUNTRIES.find((c) => c.code === code)?.name ?? code;
}

/** Returns the primary IANA timezone for a country code, or 'UTC' if not found. */
export function defaultTimezoneForCountry(code: string): string {
  return COUNTRIES.find((c) => c.code === code)?.timezone ?? 'UTC';
}

/** Returns the ISO 4217 currency code for a country, or 'USD' if not found. */
export function currencyForCountry(code: string): string {
  return COUNTRIES.find((c) => c.code === code)?.currency ?? 'USD';
}
